import doSomething from "./types";
import functions from "./functions";
import init from "./arrays";
init();
functions();
doSomething();
const user: string = "galamouyal88@gmail.com";
const age: number = 34;
console.log(user, age);
// console.log(age.toLweCase());
